### ISSUE TITLE
Port to server-side? (Feature Request)

### ISSUE THREAD

**Issue by fennecr** [rebane2001/aimobs#1]
This should work server-side, right?

**Comment by rebane2001** [comment]
No, this is single-player only. I have a PaperMC plugin version of the mod (seen [here](https://www.youtube.com/watch?v=O9pqcqNedMM)), but I haven't looked into releasing it. Originally I didn't release it because I was afraid of people using it on their public servers, which is not a good idea.

**Comment by fennecr** [comment]
Oh, Alright.
