### ISSUE TITLE
Constant Error Getting Response

### ISSUE THREAD

**Issue by Nimportance** [rebane2001/aimobs#5]
I made a new platform OpenAI account to attempt to get rid of the Error Getting Response problem. Even with zero usage of credits with a fresh start the Error message is still happening. Can you please find out what’s going on cause this is starting to get annoying for real no offense.

**Comment by rebane2001** [comment]
Can you use the OpenAI playground on your account?

**Comment by Nimportance** [comment]
> Can you use the OpenAI playground on your account?

Nope, usage limit has been reached. I don't know why this is happening to me.

**Comment by rebane2001** [comment]
Then the issue is not related to this mod, but your OpenAI account.

**Comment by piterr140K** [comment]
hi do you know how to fix  Error Getting Response problem but i have this all time i started using this mod doday and i have my api key and put and when im crouching and click on a mob its says in chat  Error Getting Response and how to fix this ?
