### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by makarikk** [rebane2001/aimobs#8]
The mod works properly, but there is one problem, when the animal speaks English or any similar language, then everything goes fine. But if you turn to an animal in a language that is written in Cyrillic, such as Ukrainian or Russian, then the answer will be interrupted in half. That is, the message simply will not be complete, after about 12 words it simply breaks off. How to fix the error?
![2023-05-04_19 43 39](https://user-images.githubusercontent.com/132408754/236298170-bccb12b7-c75c-4642-8343-bb44d23c99af.png)

**Comment by Eianex** [comment]
Fixed issue on my branch with [ukranian release](https://github.com/Eianex/aimobs/releases) with expanded tokens. Can edit this issue as closed @rebane2001 or @makarikk

**Comment by rebane2001** [comment]
Thank you, I'll add a link to your repo in the README
